### PR TITLE
V1.2.0

### PR DESCRIPTION
**Pull request by jpzk**
- Build against Apache Kafka 0.10.2
- Added support for Scala 2.12.1
- Added .stateTable and .windowStateTable method for retrieving the contant of the state store as Map
- Added contributors file
- Removed dependencies to Log4j and Slf4j
- Updated RocksDB version to 5.0.1
- Updated ScalaTest version to 3.0.1
- Added assertions in the test for input validation

### CODE REVIEW

**Comment by jpzk** [comment]
As discussed, waiting for the state store changes.

**Comment by jpzk** [comment]
@hrafzali, for me the MAX_VALUE issue did not arise, maybe a caching problem there was a wrong method header though. I also shortened the fixture values. Added documentation for stateTable and windowStateTable and added some extra tests for input validations.

**Comment by hrafzali** [comment]
@jpzk LGTM!

**Comment by jpzk** [comment]
Allright, I am going to merge and then release

**Pull request merged**
