### PR TITLE
Update to kafka 2.1 and scala DSL

### PR DESCRIPTION
**Pull request by mdziemianko**
Update to use Kafka 2.1 and conversion to use new Scala DSL (instead of the old/Java DSL).

### CODE REVIEW

**Comment by jpzk** [comment]
I'll add the scala-dsl stuff in the next minor version!

**Comment by mdziemianko** [comment]
No worries:) Do you want me to resolve the conflicts or do you have your own branch?

**Comment by jpzk** [comment]
It would be great if you could rebase to master 👍 once you're ready i'll prepare a release/2.2.1 branch with your changes!

**Comment by mdziemianko** [comment]
done!

**Pull request merged**
