### PR TITLE
Support Kafka 2.1.0

### PR DESCRIPTION
**Pull request by mowczare**

### CODE REVIEW

**Comment by chadjosephson-octanner** [comment]
Please review/merge this PR.

**Comment by PeterFras** [comment]
Any update on this?

**Comment by jpzk** [comment]
Sorry guys, I didn't see this ... will take it on def this evening.

**Comment by jpzk** [comment]
https://twitter.com/madewithtea/status/1083289403336871937, do you have a twitter handle @mowczare would like to mention you 👍

**Comment by mowczare** [comment]
I don't use twitter, my apologies ;)

**Pull request merged**
